Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

In [27]:
import numpy as np
def my_vander(x, N=None, increasing=False):
    
    """ 
    This is the implementation of the Alexandre-Theophile Vandermonde matrix 
    in which columns of the output matrix are powers of the input vector.
        
    Arguments:
    
    x: One dimensional numpy array 
    
    N: number of columns in the output.If N is not specified then N=len(x)
       
    Increasing: 
                By default the increasing is False,the powers decrease from left to right.
                If increasing is True then it is reversed.
     
    output:
    
    It returns a n dimensional vandermonde matrix.If Increasing is False then elements of the column 
    are x^N-1,x^N-2,....x^0  If Increasing is True then elements of the column  
    are x^0,x^1,......x^N-1.
       
    """
   
    if x.ndim != 1:
        return ("x should be a one dimensional array or sequence.") 
    
    if N is None:
        N=len(x)
   
    op = np.column_stack([x**(N-i-1) for i in range(N)])
    if increasing:
        y = op[:, ::-1]
        return y
    else:
        return op



In [32]:
#If N is None,it takes length of x

x=np.array([1,2,3,4,5])
output = my_vander(x)
print(output)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [33]:
#If x is not a one dimensional array

x=np.array([[1,2,3,4],[2,3,4,5]])
output = my_vander(x)
print(output)

x should be a one dimensional array or sequence.


In [34]:
#If Increasing is True and pass N value

x=np.array([1,2,3,4])
output = my_vander(x,3,increasing=True)
print(output)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [35]:
#If Increasing is False and pass N value

x = np.array([1,2,3,4])
output = my_vander(x,3,increasing=False)
print(output)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
